### ISSUE TITLE
create-graphqlgen terminates with an error

### ISSUE THREAD

**Issue by nunovieira** [prisma/graphqlgen#390]
## Description
`npm init graphqlgen my-app` terminates with an error.

## Steps to reproduce
Execute `npm init graphqlgen my-app` and choose any of the templates.

## Expected results
Create a GraphQL server in `my-app`.

## Actual results
```
$ npm init graphqlgen my-app
npx: installed 213 in 14.109s
? Choose a GraphQL server template? typescript-yoga (GraphQL Yoga template with TypeScript)
TypeError: Cannot read property 'repo' of undefined
(...)
```

## Versions
- graphqlgen: 0.5.0
- OS name and version: macOS 10.14.2

**Comment by jasonkuhrt** [comment]
A complete example:

```
❯ graphqlgen -v
0.5.0

❯ yarn -s create graphqlgen
warning "apollo > apollo-engine-reporting > graphql-extensions@0.1.2" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphqurl > apollo-link@1.2.3" has incorrect peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0".
warning "graphqurl > subscriptions-transport-ws@0.9.15" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.1 || ^14.0.2".
warning "graphqurl > apollo-cache-inmemory@1.2.10" has incorrect peer dependency "graphql@0.11.7 || ^0.12.0 || ^0.13.0".
warning "graphqurl > apollo-client@2.4.2" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "graphqurl > apollo-link-http@1.5.5" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "graphqurl > graphql-language-service-interface@1.3.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphqurl > graphql-language-service-utils@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphqurl > apollo-link-http > apollo-link-http-common@0.2.5" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "graphqurl > graphql-language-service-interface > graphql-config@2.0.1" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphqurl > graphql-language-service-interface > graphql-language-service-parser@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphqurl > graphql-language-service-interface > graphql-language-service-types@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "prisma > prisma-cli-core > prisma-generate-schema > tslint-eslint-rules@5.4.0" has unmet peer dependency "tslint@^5.0.0".
warning "prisma > prisma-cli-core > prisma-generate-schema > tslint-eslint-rules@5.4.0" has unmet peer dependency "typescript@^2.2.0 || ^3.0.0".
warning "prisma > prisma-cli-core > prisma-generate-schema > tslint-eslint-rules > tsutils@3.3.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev".
[############################################################################################################################################################################] 1953/1953?? Choose a GraphQL server template? typescript-yoga (GraphQL Yoga template with TypeScript)
? Where should we scaffold graphql server? .
TypeError: Cannot read property 'repo' of undefined
    at getGraphQLGenTemplateRepositoryTarInformation (/Users/jasonkuhrt/.config/yarn/global/node_modules/create-graphqlgen/dist/loader.js:35:34)
    at Object.<anonymous> (/Users/jasonkuhrt/.config/yarn/global/node_modules/create-graphqlgen/dist/loader.js:21:21)
    at Generator.next (<anonymous>)
    at /Users/jasonkuhrt/.config/yarn/global/node_modules/create-graphqlgen/dist/loader.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jasonkuhrt/.config/yarn/global/node_modules/create-graphqlgen/dist/loader.js:3:12)
    at Object.loadGraphQLGenStarter (/Users/jasonkuhrt/.config/yarn/global/node_modules/create-graphqlgen/dist/loader.js:20:12)
    at /Users/jasonkuhrt/.config/yarn/global/node_modules/create-graphqlgen/dist/index.js:103:18
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jasonkuhrt/.config/yarn/global/node_modules/create-graphqlgen/dist/index.js:5:58)
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-graphqlgen
Arguments:
Directory: /Users/jasonkuhrt/projects/dialogue/tmp-graphql-init-bug
Output:
```

**Comment by nunovieira** [comment]
Release a new version of create-graphqlgen? It simply doesn't work ATM.
Weird no one notice this before. The regression was introduced more than two months ago!

**Comment by jasonkuhrt** [comment]
> Release a new version of create-graphqlgen? It simply doesn't work ATM.

I am just aligning with some collaborators about how mono-repo releases should be done. I am confident we can get a publish done today. Sorry I can't link to that slack discussion it wasn't in a public channel.

> Weird no one notice this before. The regression was introduced more than two months ago!

Agree, was surprised myself!

**Comment by jasonkuhrt** [comment]
@nunovieira [published](https://github.com/prisma/graphqlgen/releases/tag/v0.5.1)
